# Generated by Django 4.2.2 on 2023-08-04 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='alldata',
            fields=[
                ('dataid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('slug', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=300)),
                ('image', models.ImageField(default='', upload_to='tze/images')),
                ('testimoniallink', models.CharField(default='', max_length=300)),
                ('ytlink', models.CharField(default='', max_length=300)),
                ('benifits', models.CharField(default='', max_length=300)),
                ('how_to_use', models.CharField(default='', max_length=400)),
                ('doc_link', models.CharField(default='', max_length=300)),
                ('net_Qty', models.CharField(default='', max_length=100)),
                ('pack_of', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
