# Generated by Django 4.2.2 on 2023-08-09 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agri_iot', '0002_requestdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='pricingmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planName', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='requestdata',
            name='ph',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='requestdata',
            name='humidity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='requestdata',
            name='nitrogen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='requestdata',
            name='phosphorus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='requestdata',
            name='potassium',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='requestdata',
            name='rainfall',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='requestdata',
            name='soil_moisture',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='requestdata',
            name='temperature',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='userdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
