# Generated by Django 4.2.2 on 2023-08-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_iot', '0003_pricingmodel_requestdata_ph_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingmodel',
            name='planName',
        ),
        migrations.RemoveField(
            model_name='pricingmodel',
            name='price',
        ),
        migrations.RemoveField(
            model_name='pricingmodel',
            name='slug',
        ),
        migrations.AddField(
            model_name='pricingmodel',
            name='pri_Annually_price',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pricingmodel',
            name='pri_Annually_slug',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='pricingmodel',
            name='pri_Monthly_price',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pricingmodel',
            name='pri_Monthly_slug',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='pricingmodel',
            name='pri_detailslist',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='pricingmodel',
            name='pri_planName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pricingmodel',
            name='pri_slug',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pricingmodel',
            name='pri_tag',
            field=models.CharField(default='', max_length=80),
        ),
    ]
