# Generated by Django 4.2.2 on 2023-08-10 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agri_iot', '0005_remove_pricingmodel_pri_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='phoneNum',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='userDailyChatRequests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='userDailyRecRequests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='userDailyServerRequests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='userPlan',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='userPlanStartDate',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
