# Generated by Django 4.2.2 on 2023-08-15 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agri_iot', '0006_userdetails_phonenum_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDayCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userDayCountServerRequests', models.IntegerField(default=0)),
                ('userDayCountChatRequests', models.IntegerField(default=0)),
                ('userDayCountRecRequests', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='RequestData',
            new_name='StoreData',
        ),
        migrations.DeleteModel(
            name='alldata',
        ),
        migrations.RenameField(
            model_name='userdetails',
            old_name='userDailyChatRequests',
            new_name='userDailyLimitChatRequests',
        ),
        migrations.RenameField(
            model_name='userdetails',
            old_name='userDailyRecRequests',
            new_name='userDailyLimitRecRequests',
        ),
        migrations.RenameField(
            model_name='userdetails',
            old_name='userDailyServerRequests',
            new_name='userDailyLimitServerRequests',
        ),
    ]
