# Generated by Django 4.2.2 on 2023-08-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_iot', '0007_userdaycount_rename_requestdata_storedata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='userApiKey',
            field=models.CharField(default='', max_length=50),
        ),
    ]
