# Generated by Django 4.2.2 on 2023-08-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_iot', '0008_userdetails_userapikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='user',
            field=models.CharField(default='', max_length=50),
        ),
    ]
