# Generated by Django 4.2.2 on 2023-08-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_iot', '0010_alter_storedata_user_alter_userdaycount_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storedata',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='storedata',
            name='dateStamp',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='storedata',
            name='ph',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='storedata',
            name='timeStamp',
            field=models.CharField(default='', max_length=50),
        ),
    ]
